linux-port: Rename pthread_mutex_t variable 'lock'
lock is also used by libc++ in std namespace and using it here causes
clang to fail e.g.

dibbler-client.cpp:47:25: error: reference to 'lock' is ambiguous
    pthread_mutex_lock(&lock);
                        ^
../../../../../../../workspace/sources/dibbler/Port-linux/dibbler-client.cpp:29:26: note: candidate found by name lookup is 'lock'
extern ::pthread_mutex_t lock;
                         ^
/mnt/a/yoe/build/tmp/work/aarch64-yoe-linux/dibbler/1.0.1+1.0.2RC1+gitc4b0ed52e751da7823dd9a36e91f93a6310e5525-r0/recipe-sysroot/usr/include/c++/v1/mutex:446:1: note: candidate found by name lookup is 'std::__1::lock'
lock(_L0& __l0, _L1& __l1, _L2& __l2, _L3& ...__l3)

Signed-off-by: Khem Raj <raj.khem@gmail.com>